class Columns:
    TRACK_NAME = "Track Name"
    ARTIST_NAMES = "Artist Name(s)"
    ALBUM_NAME = "Album Name"
    ARTIST_GENRES = "Artist Genres"
    POPULARITY = "Popularity"
    KEY = "Key"
    MODE = "Mode"
    DURATION = "Track Duration (ms)"
    LOUDNESS = "Loudness"
    TEMPO = "Tempo"
    TIME_SIGNATURE = "Time Signature"
    DANCEABILITY = "Danceability"
    ENERGY = "Energy"
    SPEECHINESS = "Speechiness"
    ACOUSTICNESS = "Acousticness"
    INSTRUMENTALNESS = "Instrumentalness"
    LIVENESS = "Liveness"
    VALENCE = "Valence"

class DataColors:
    SIMILAR_TRACKS = "#5cd0ed"
    GENRE = "#6f0d96"
    ARTIST = "#06806b"
    POPULARITY = "#19b065"
    KEY = "#35606d"
    MODE = "#0e3d4b"
    DURATION = "#ed5c5e"
    LOUDNESS = "#570202"
    TEMPO = "#5f5f5f"
    TIME_SIGNATURE = "#272727"
    
    # Audio Features (Yüzdelik Sütunlar)
    DANCEABILITY = "#853d9b"
    ENERGY = "#f58f2f"
    SPEECHINESS = "#15c7a0"
    ACOUSTICNESS = "#b48a52"
    INSTRUMENTALNESS = "#e489dc"
    LIVENESS = "#d63693"
    VALENCE = "#e0b010" 


A5_LANDSCAPE = (210, 148)   # 210mm x 148mm
A4_LANDSCAPE = (297, 210)   # 297mm x 210mm
A3_LANDSCAPE = (420, 297)   # 420mm x 297mm
A2_LANDSCAPE = (594, 420)   # 594mm x 420mm

PERCENTAGE_COLUMNS = [
    Columns.TEMPO,
    Columns.DANCEABILITY,
    Columns.VALENCE ,
    Columns.ENERGY, 
    Columns.SPEECHINESS, 
    Columns.INSTRUMENTALNESS,
    Columns.ACOUSTICNESS, 
    Columns.LIVENESS, 
]

feature_weights = {
    Columns.DANCEABILITY    : 0.1,
    Columns.ENERGY          : 1.0,
    Columns.VALENCE         : 1.0,        # Mood önemli
    Columns.ACOUSTICNESS    : 0.5,
    Columns.INSTRUMENTALNESS: 0.5,
    Columns.LIVENESS        : 0.1,
    Columns.SPEECHINESS     : 0.5,
    Columns.TEMPO           : 0.5,
}

# PDF Layout and Metadata
REPORT_TITLE = "Spotify Playlist Analytics"
FOOTER_TEXT = "Generated by Spotify Playlist Analyzer - Engineer Edition"

# Default font sizes
TITLE_FONT_SIZE = 28
SUBTITLE_FONT_SIZE = 16

# Network Analysis Settings
MAX_EDGES_PER_NODE = 3 
SIMILARITY_THRESHOLD = 0.20
GLOB_DIST_COL = "Global_Distance"